---
authlogic:
  :options:
    :version: ~> 2.0
will_paginate:
  :options:
    :version: ~> 2.2
    :lib: will_paginate
searchlogic:
  :options:
    :lib: searchlogic
    :version: ~> 2.3
matthuhiggins-foreigner:
  :options:
    :lib: foreigner
formtastic:
  :options:
    :version: ~> 0.9
haml:
  :options:
    :version: ~> 2.2
  :if: template_engine == "haml" || design == "compass"
compass:
  :options:
    :lib: compass
  :if: design == "compass"
compass-960-plugin:
  :options:
    :lib: ninesixty
  :if: "design == 'compass' && compass_css_framework =~ /960/"
inherited_resources:
  :options:
    :lib: inherited_resources
    :version: >= 0.9.0
  :if: controller_type == "inherited_resources"
erubis:
  :options:
    :version: >= 2.6.5
paperclip:
  :options:
    :version: >= 2.3
jammit:
  :options:
    :version: >= 0.3
:carmen:
  :options:
    :version: >= 0.1
:health_monitor:
  :options:
    :version: >= 0.1.4
# Optional exception handling
hoptoad_notifier:
  :options:
    :version: >= 2.1.3
  :if: exception_handling == "hoptoad"

# development only
inaction_mailer:
  :options:
    :lib: inaction_mailer/force_load
    :env: development
  :if: mail_in_development == "inaction_mailer"
ffmike-query_trace:
  :options:
    :lib: query_trace
    :source: http://gems.github.com
    :env: development
bullet:
  :options:
    :env: development
annotate:
  :options:
    :lib: annotate
    :env: development
rcov:
  :options:
    :env: development
metric_fu:
  :options:
    :version: >= 1.3
    :lib: metric_fu
    :env: development

# test only
shoulda:
  :options:
    :lib: shoulda
    :env: test
ffmike-test_benchmark:
  :options:
    :lib: test_benchmark
    :source: http://gems.github.com
    :env: test
webrat:
  :options:
    :env: test
rr:
  :options:
    :version: ">=0.10.3"
    :env: test
  :if: @mocking == "rr"
mocha:
  :options:
    :version: ">=0.9.7"
    :env: test
  :if: @mocking == "mocha"
rcov:
  :options:
    :env: test
metric_fu:
  :options:
    :version: >= 1.3
    :lib: metric_fu
    :env: test

